apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linode-dns-update.fullname" . }}-secrets
  labels:
    {{- include "linode-dns-update.labels" . | nindent 4 }}
stringData:
  LINODE_TOKEN: {{ .Values.linode.token }}
